name: Build packages

on:
  release:
    types: [published]
  push:
    branches: [master]
    tags:
      - v*
      - '!v2020*'
    paths:
      - ".github/workflows/build.yml"
      - "libremesh.mk"
      - "packages/**"
  workflow_dispatch:

jobs:
  # Build all packages for x86_64 using the openwrt sdk
  # use latest branch of openwrt with opkg to produce feed at https://feed.libremesh.org/master
  # use main branch of openwrt with apk to produce feed at https://feed.libremesh.org/apk/master
  # NOTE: this doesn't sign packages for apk
  build:
    name: Build ${{ matrix.version }} ${{ github.ref }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - { version: main, output_path: 'apk/'}
          - { version: openwrt-24.10, output_path: ''}
    steps:
      - uses: actions/checkout@v4

      - name: Build packages
        uses: openwrt/gh-action-sdk@v7
        env:
          ARCH: "x86_64-${{ matrix.version }}"
          FEEDNAME: "libremesh"
          IGNORE_ERRORS: "n m y"
          KEY_BUILD: "${{ matrix.version != 'main' && secrets.KEY_BUILD || '' }}"
          INDEX: 1
          NO_DEFAULT_FEEDS: 1
          NO_REFRESH_CHECK: 1
          NO_SHFMT_CHECK: 1
          # V: sc

      - name: Set package destination
        run: |
          export TAG=$(echo "${{ github.ref }}" | cut -d '/' -f 3- | perl -pe 's/v([0-9])/$1/')
          echo "$TAG"
          echo "DEST_DIR=$TAG" >> $GITHUB_ENV

      - name: Upload packages to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: libremesh/lime-feed
          publish_dir: bin/packages/x86_64/libremesh/
          destination_dir: ${{ matrix.output_path }}${{ env.DEST_DIR }}

#     - name: Upload packages to S3
#       uses: jakejarvis/s3-sync-action@master
#       with:
#         args: --acl public-read --follow-symlinks --delete
#       env:
#         AWS_S3_BUCKET: libremesh
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
#         SOURCE_DIR: bin/packages/x86_64/libremesh/
#         DEST_DIR: ${{ env.DEST_DIR }}
